name: fina-6333
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab-git
  - numpy
  - pandas
  - pip
  - scipy
  - statsmodels
  - pip:
    - otter-grader
    - yfinance
    - pandas-datareader
    - requests-cache
